### PR TITLE
Extract miner names from coinbase inputs

### PR DESCRIPTION
**Pull request by marpme**
This will take coinbase inputs signatures and eventually extact names from it other wise it shows unknown miner as it's name.

One example is here: 

image

### CODE REVIEW

**Comment by marpme** [comment]
While reading this we should definitely add an escape of those parsed chars :)

**Comment by peengo** [comment]
> 
> 
> While reading this we should definitely add an escape of those parsed chars :)

https://vuejs.org/v2/guide/security.html#HTML-content

If you mean like this, then its already escaped at rendering :)

**Comment by marpme** [comment]
@peengo oh well, that's super awesome. Thank you for pointing that out :) 
I don't see any blocker anymore!

**Comment by peengo** [comment]
@marpme approved and edited the code a bit. Thank you for your support :)

**Pull request merged**
